name: "Build NixOS Image"
on:
  workflow_dispatch:
    inputs:
      target_name:
        description: Target Configuration Name
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: fayash
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Disko Image
        run: |
          nix build .#nixosConfigurations.${{ github.event.inputs.target_name }}.config.system.build.diskoImagesScript
          ./result --build-memory 4096
          mkdir -p output
          cp -L *.raw output/

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: nixos-disko-image
          path: output/*.raw
          retention-days: 1
